import reflex as rx


class LanguageState(rx.State):
    current_lang: str = "en"
    is_rtl: bool = False
    translations: dict[str, dict[str, str]] = {
        "en": {
            "dashboard": "Dashboard",
            "athletes": "Athletes",
            "coaches": "Coaches",
            "age_categories": "Age Categories",
            "payments": "Payments",
            "attendance": "Attendance",
            "competitions": "Competitions",
            "reports": "Reports",
            "settings": "Settings",
            "logout": "Logout",
            "welcome_back": "Welcome back",
            "total_athletes": "Total Athletes",
            "active_coaches": "Active Coaches",
            "monthly_revenue": "Monthly Revenue",
            "unpaid_fees": "Unpaid Fees",
            "quick_actions": "Quick Actions",
            "add_athlete": "Add Athlete",
            "record_payment": "Record Payment",
            "add_result": "Add Result",
            "recent_activity": "Recent Activity",
            "no_activity": "No recent activity recorded.",
            "new_athlete_joined": "New athlete joined: ",
            "search": "Search...",
            "full_name": "Full Name",
            "phone": "Phone",
            "email": "Email",
            "save": "Save",
            "cancel": "Cancel",
            "delete": "Delete",
            "edit": "Edit",
            "actions": "Actions",
            "date": "Date",
            "status": "Status",
            "amount": "Amount",
            "paid": "Paid",
            "unpaid": "Unpaid",
            "overdue": "Overdue",
            "partial": "Partial",
            "present": "Present",
            "absent": "Absent",
            "late": "Late",
            "import_csv": "Import CSV",
            "export_pdf": "Export PDF",
            "belt_rank": "Belt Rank",
            "gender": "Gender",
            "dob": "Date of Birth",
            "guardian": "Guardian",
            "address": "Address",
            "specialization": "Specialization",
            "description": "Description",
            "min_age": "Min Age",
            "max_age": "Max Age",
            "category": "Category",
            "result": "Result",
            "location": "Location",
            "monthly_fee": "Monthly Subscription Fee",
            "yearly_license": "Annual License Fee",
            "generate_id": "Generate ID Card",
            "backup_db": "Backup Database",
            "restore_db": "Restore Database",
            "theme": "Theme",
            "language": "Language",
            "login_title": "Galia Club Karate Manager",
            "sign_in": "Sign In",
            "username": "Username",
            "password": "Password",
            "login_error": "Invalid username or password",
            "scan_qr": "Scan QR",
            "notifications": "Notifications",
            "unpaid_alert": "athletes have unpaid fees this month.",
            "license_alert": "athletes have licenses expiring soon.",
        },
        "fr": {
            "dashboard": "Tableau de bord",
            "athletes": "Athlètes",
            "coaches": "Entraîneurs",
            "age_categories": "Catégories d'âge",
            "payments": "Paiements",
            "attendance": "Présences",
            "competitions": "Compétitions",
            "reports": "Rapports",
            "settings": "Paramètres",
            "logout": "Déconnexion",
            "welcome_back": "Bon retour",
            "total_athletes": "Total Athlètes",
            "active_coaches": "Entraîneurs Actifs",
            "monthly_revenue": "Revenu Mensuel",
            "unpaid_fees": "Impayés",
            "quick_actions": "Actions Rapides",
            "add_athlete": "Ajouter Athlète",
            "record_payment": "Enregistrer Paiement",
            "add_result": "Ajouter Résultat",
            "recent_activity": "Activité Récente",
            "no_activity": "Aucune activité récente.",
            "new_athlete_joined": "Nouvel athlète inscrit : ",
            "search": "Rechercher...",
            "full_name": "Nom Complet",
            "phone": "Téléphone",
            "email": "Email",
            "save": "Enregistrer",
            "cancel": "Annuler",
            "delete": "Supprimer",
            "edit": "Modifier",
            "actions": "Actions",
            "date": "Date",
            "status": "Statut",
            "amount": "Montant",
            "paid": "Payé",
            "unpaid": "Non Payé",
            "overdue": "En Retard",
            "partial": "Partiel",
            "present": "Présent",
            "absent": "Absent",
            "late": "En Retard",
            "import_csv": "Importer CSV",
            "export_pdf": "Exporter PDF",
            "belt_rank": "Grade (Ceinture)",
            "gender": "Sexe",
            "dob": "Date de Naissance",
            "guardian": "Tuteur",
            "address": "Adresse",
            "specialization": "Spécialisation",
            "description": "Description",
            "min_age": "Age Min",
            "max_age": "Age Max",
            "category": "Catégorie",
            "result": "Résultat",
            "location": "Lieu",
            "monthly_fee": "Frais Mensuels",
            "yearly_license": "Frais Licence Annuelle",
            "generate_id": "Générer Carte ID",
            "backup_db": "Sauvegarder BDD",
            "restore_db": "Restaurer BDD",
            "theme": "Thème",
            "language": "Langue",
            "login_title": "Galia Club Karaté Manager",
            "sign_in": "Se Connecter",
            "username": "Nom d'utilisateur",
            "password": "Mot de passe",
            "login_error": "Nom d'utilisateur ou mot de passe invalide",
            "scan_qr": "Scanner QR",
            "notifications": "Notifications",
            "unpaid_alert": "athlètes ont des frais impayés ce mois-ci.",
            "license_alert": "athlètes ont des licences expirant bientôt.",
        },
        "ar": {
            "dashboard": "لوحة القيادة",
            "athletes": "الرياضيين",
            "coaches": "المدربين",
            "age_categories": "الفئات العمرية",
            "payments": "المدفوعات",
            "attendance": "الحضور",
            "competitions": "المنافسات",
            "reports": "التقارير",
            "settings": "الإعدادات",
            "logout": "تسجيل الخروج",
            "welcome_back": "مرحبا بعودتك",
            "total_athletes": "مجموع الرياضيين",
            "active_coaches": "المدربين النشطين",
            "monthly_revenue": "الإيرادات الشهرية",
            "unpaid_fees": "الرسوم غير المدفوعة",
            "quick_actions": "إجراءات سريعة",
            "add_athlete": "إضافة رياضي",
            "record_payment": "تسجيل دفع",
            "add_result": "إضافة نتيجة",
            "recent_activity": "النشاط الأخير",
            "no_activity": "لا يوجد نشاط حديث.",
            "new_athlete_joined": "انضم رياضي جديد: ",
            "search": "بحث...",
            "full_name": "الاسم الكامل",
            "phone": "الهاتف",
            "email": "البريد الإلكتروني",
            "save": "حفظ",
            "cancel": "إلغاء",
            "delete": "حذف",
            "edit": "تعديل",
            "actions": "إجراءات",
            "date": "التاريخ",
            "status": "الحالة",
            "amount": "المبلغ",
            "paid": "مدفوع",
            "unpaid": "غير مدفوع",
            "overdue": "متأخر",
            "partial": "جزئي",
            "present": "حاضر",
            "absent": "غائب",
            "late": "متأخر",
            "import_csv": "استيراد CSV",
            "export_pdf": "تصدير PDF",
            "belt_rank": "الرتبة (الحزام)",
            "gender": "الجنس",
            "dob": "تاريخ الميلاد",
            "guardian": "الولي",
            "address": "العنوان",
            "specialization": "التخصص",
            "description": "الوصف",
            "min_age": "الحد الأدنى للسن",
            "max_age": "الحد الأقصى للسن",
            "category": "الفئة",
            "result": "النتيجة",
            "location": "الموقع",
            "monthly_fee": "الاشتراك الشهري",
            "yearly_license": "رسوم الترخيص السنوي",
            "generate_id": "إنشاء بطاقة هوية",
            "backup_db": "نسخ احتياطي",
            "restore_db": "استعادة قاعدة البيانات",
            "theme": "المظهر",
            "language": "اللغة",
            "login_title": "مدير نادي غاليا للكاراتيه",
            "sign_in": "تسجيل الدخول",
            "username": "اسم المستخدم",
            "password": "كلمة المرور",
            "login_error": "اسم المستخدم أو كلمة المرور غير صالحة",
            "scan_qr": "مسح QR",
            "notifications": "إشعارات",
            "unpaid_alert": "رياضيين لديهم رسوم غير مدفوعة هذا الشهر.",
            "license_alert": "رياضيين ستنتهي تراخيصهم قريبًا.",
        },
    }

    @rx.event
    def set_language(self, lang: str):
        self.current_lang = lang
        self.is_rtl = lang == "ar"

    @rx.event
    def t(self, key: str) -> str:
        return self.translations[self.current_lang].get(key, key)